Exclude the commons-text dependency
Decathlon/tzatziki pull request #103
Opened 2022-10-24 16:07 UTC by mamdouni

A vulnerability 9.8/10 has been detected on the commons-text 1.9.0 library
Correction : 
- Exclude it
- Uprgarde to the 1.10.0 version
https://commons.apache.org/proper/commons-text/security.html
** Note ** : this dependency is used by mockserver and in its new version 5.14.0, it still uses the vulnerable library

2022-10-25 07:41 UTC, brian-mulier commented
I feel like we can simply force the version on the tzatziki-parent pom instead of excluding it ?

2022-10-25 07:45 UTC, mamdouni commented
This dependency does not seem to be used as after excluding it everything works well.

2022-10-25 08:03 UTC, brian-mulier commented
After looking further, it looks okay since we don't use any of the library feature. However be aware that Handlebars, which we use, does some kind of magic relocate after importing this library so I think it will still be vulnerable 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/69139631/197717892-0b1a2fdf-d330-46c5-a150-33dde68bcd07.png">

2022-10-25 08:44 UTC, brian-mulier commented
Also, I'm not that confident about removing a transitive dependency since it could lead to an issue later if they start to use it further.
I would prefer to upgrade the dependency through the BOM strategy, what do you think ?

2022-10-28 17:53 UTC, mamdouni commented
Oh yes, I like your idea. Less of risks
I changed my code to add the version in the parent BOM and use it in the child module

2022-11-08 13:40 UTC, mamdouni commented
@brian-mulier do you have the visibility of the release of the next version please and it will contain this fix ?

2022-11-14 10:00 UTC, brian-mulier requested changes

2022-11-14 10:00 UTC, brian-mulier commented on mockfaster/pom.xml
> +        </dependency>
I may be wrong but I think you don't even need to import it as long as it is fetched through transitive dependency, can you check if it is the case through maven dependency helper ?
The parent bom should override the transitive dependency version.

2022-11-14 10:01 UTC, brian-mulier commented on mockfaster/pom.xml
> +        </dependency>
@mamdouni I was in vacation sorry, I will do the version release as soon as you check this.

2022-11-21 15:20 UTC, mamdouni commented on mockfaster/pom.xml
> +        </dependency>
yep thanks for your reply,
As you said, the transitive dependency has been forced by the parent bom version ( thanks for the tip )
![image](https://user-images.githubusercontent.com/61866853/203091581-2c4f277f-32b8-4d14-a7ab-bf2ed4f9298b.png)

2022-11-21 15:31 UTC, mamdouni commented on mockfaster/pom.xml
> +        </dependency>
As requested, i did the changes

2022-11-22 11:00 UTC, merged