Split HttpInterceptor to avoid spring web / reactive forced dependency
Decathlon/tzatziki pull request #160
Opened 2023-05-12 13:15 UTC by alexandrepa

With the version 1.3.9, we've made spring-boot-starter-webflux as _provided_. 
Trying to migrate my app to version 1.3.9 I was forced to add spring-boot-starter-webflux in my dependencies because HttpInterceptor in tzatziki-spring need it.
So I think it's best to use @Conditional spring condition to only inject bean related to servlet or reactive spring web dependencies depending of the application which is using tzatziki. 

I am not strongly convinced of my approach so I'm open to suggestions. 
I have separate each type of interceptor tzatziki is putting to be sure to only try to intercept classes that are available on the classpath.

2023-05-12 13:34 UTC, alexandrepa commented
I've just see that there already an issue on this matter : #99

2023-05-17 13:54 UTC, brian-mulier requested changes

2023-05-17 13:54 UTC, brian-mulier commented on tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/HttpInterceptorDefinition.java
> +    T rewrite(T webClient);
```suggestion
    T withUrlRewrite(T webClient);
```
Seems better ?

2023-05-17 13:57 UTC, brian-mulier requested changes

2023-05-17 13:57 UTC, brian-mulier commented on tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/HttpInterceptorDefinition.java
> +    T rewrite(T webClient);
```suggestion
    T rewrite(T httpClient);
```

2023-05-17 13:58 UTC, brian-mulier commented on tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/HttpInterceptorDefinition.java
> +    T rewrite(T webClient);
Simply modify this to prevent confusion with WebClient :+1:

2023-05-23 09:56 UTC, CGUYOT26 approved these changes

2023-05-23 09:56 UTC, merged